### ISSUE TITLE
Incompatible shapes: [100,4] vs [10000, 4]

### ISSUE THREAD

**Issue by imsrgadich** [ICL-SML/Doubly-Stochastic-DGP#16]
Hi @hughsalimbeni, 

I'm replicating your [notebook](https://github.com/ICL-SML/Doubly-Stochastic-DGP/blob/master/demos/demo_regression_UCI.ipynb) with a Spectral Mixture Kernel [2] (only addition is you need to run `sm_init` [1] before calling the SM kernel function).  I'm getting this error when I run the optimizer `AdamOptimizer(0.01).minimize(m, maxiter=5000)`. 

```
InvalidArgumentError (see above for traceback): Incompatible shapes: [100,4] vs. [10000,4]
[[Node: gradients/DGP-ca7720f0-47/add_grad/BroadcastGradientArgs = BroadcastGradientArgs[T=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"](gradients/DGP-ca7720f0-47/conditional/ExpandDims_7_grad/Shape, DGP-ca7720f0-47/conditional/Shape_5)]]
```
Full error is given in [3]. On doing some [research](https://stackoverflow.com/questions/42822844/tensorflow-incompatible-shapes-100-155-vs-128-155-when-combining-cnn-and) I found out that the error is due to **minibatch_size** (which is right). But I'm still not able to figure the changes to overcome this error. Can you please suggest something. Thank you. 

[1] **Initializing the SM hyperparameters**: 
        `weights, means, scales = sm_init(train_x=X, train_y=Y, num_mixtures=Q)`

[2] **Spectral Mixture Kernel**:
```
import tensorflow as tf
import numpy as np
from gpflow.decors import params_as_tensors
from gpflow.params import Parameter
from gpflow.kernels import Kernel
from gpflow import transforms

class SpectralMixture(Kernel):
    def __init__(self, num_mixtures=1, mixture_weights=None,\
                 mixture_scales=None,mixture_means=None,\
                 input_dim=1,active_dims=None,name=None):
        """
        - num_mixtures is the number of mixtures; denoted as Q in
        Wilson 2013.
        - mixture_weights
        - mixture_variance is
        - mixture_means is the list (or array) of means of the
        mixtures.
        - input_dim is the dimension of the input to the kernel.
        - active_dims is the dimension of the X which needs to be used.

        References:
        http://hips.seas.harvard.edu/files/wilson-extrapolation-icml-2013_0.pdf
        http://www.cs.cmu.edu/~andrewgw/typo.pdf
        """
        super().__init__(input_dim,active_dims,name=name)
        # Q(num_of_mixtures)=1 then SM kernel is SE Kernel.
        if num_mixtures == 1:
            print("Using default mixture = 1")

        # number of mixtures is non trainable.
        self.num_mixtures = Parameter(num_mixtures,trainable=False)
        self.mixture_weights = Parameter(mixture_weights)
        self.mixture_scales = Parameter(mixture_scales,transform=transforms.positive)
        self.mixture_means = Parameter(mixture_means)

    @params_as_tensors
    def K(self, X1, X2=None):
        if self.mixture_weights == None or self.mixture_means == None \
                                      or self.mixture_scales == None:
                raise RuntimeError('Parameters of spectral mixture kernel not initialized.\
                                    Run `sm_kern_object.initialize_(train_x,train_y)`.')
                # initialization can only be done by user as it needs target data as well.
        if X2 is None:
            X2 = X1

        # get absolute distances
        X1 = tf.transpose(tf.expand_dims(X1, -1), perm=[1, 0, 2])  # D x N1 x 1
        X2 = tf.expand_dims(tf.transpose(X2, perm=[1, 0]), -2)  # D x N2 x 1

        r = tf.transpose(tf.abs(tf.subtract(X1, X2)), perm=[0, 2, 1])  # D x N1 x N2


        cos_term = tf.multiply(tf.tensordot(self.mixture_means, r, axes=((1),(0))), 2. * np.pi)
        # num_mixtures x N1 x N2

        scales_expand = tf.expand_dims(tf.expand_dims(self.mixture_scales, -2), -2)
                                                                # D x 1 x 1 x num_mixtures
        r_tile = tf.tile(tf.expand_dims(r,-1),(1,1,1,self.num_mixtures))
                                                               # D x N x N x num_mixtures
        exp_term = tf.multiply(tf.transpose(tf.reduce_sum(tf.square(tf.add(r_tile, scales_expand)), 0)\
                                            ,perm=[2, 0, 1]), -2. * np.pi ** 2)

        # num_mixtures x N1 x N2
        weights = tf.expand_dims(tf.expand_dims(self.mixture_weights,-1),-1)
        weights = tf.tile(weights,(1,tf.shape(X1)[1],tf.shape(X2)[1]))
        return tf.reduce_sum(tf.multiply(weights,tf.multiply(tf.exp(exp_term),tf.cos(cos_term))),0)


    @params_as_tensors
    def Kdiag(self, X):

        # just the sum of weights. Weights represent the signal
        # variance.
        return tf.fill(tf.stack([tf.shape(X)[0]]),tf.reduce_sum(self.mixture_weights))

        # tf.tile(tf.reduce_sum(self.mixture_weights,0), tf.shape(X)[0])
        # tf.fill(tf.stack([tf.shape(X)[0]]),tf.reduce_sum(self.mixture_weights),0)


def sm_init(train_x, train_y, num_mixtures):
    """
    For initialization of the parameters for the Spectral Mixture
    Kernel.

    :param train_x: input data
    :param train_y: target data
    :param num_mixtures: number of mixtures
    :return: param_name       dimensions
             ----------       ----------
             mixture weights| num_mixtures x 1
             mixture means  | num_mixtures x input_dim
             mixture scales | input_dim x num_mixtures
    """
    assert isinstance(num_mixtures, int)
    assert train_x.shape[0] == train_y.shape[0]

    input_dim = np.shape(train_x)[1]  # type: int

    if np.size(train_x.shape) == 1:
        train_x = np.expand_dims(train_x ,-1)

    if np.size(train_x.shape) == 2:
        train_x = np.expand_dims(train_x ,0)

    train_x_sort = np.copy(train_x)
    train_x_sort.sort(axis=1)

    max_dist = np.squeeze(train_x_sort[: ,-1, :] - train_x_sort[: ,0, :])

    min_dist_sort = np.squeeze(np.abs(train_x_sort[: ,1:, :] - train_x_sort[: ,:-1, :]))
    min_dist = np.zeros([input_dim] ,dtype=float)

    # min of each data column could be zero. Hence, picking minimum which is not zero
    for ind in np.arange(input_dim):
        try:
            min_dist[ind] = min_dist_sort[np.amin(np.where(min_dist_sort[:,ind] > 0), axis=1), ind]
        except:
            min_dist[ind] = min_dist_sort[np.amin(np.where(min_dist_sort > 0), axis=1)]


    # for random restarts during batch processing. We need to initialize at every
    # batch. Lock the seed here.
    seed= np.random.randint(low=1 ,high=2**31)
    np.random.seed(seed)

    # Inverse of lengthscales should be drawn from truncated Gaussian |N(0, max_dist^2)|
    # dim: Q x D
    # mixture_scales = tf.multiply(,tf.cast(max_dist,dtype=tf.float32)**(-1)

    mixture_scales = (np.multiply(np.abs(np.random.randn(num_mixtures,input_dim)),
                                         np.expand_dims(max_dist ,axis=0)))**(-1)

    # Draw means from Unif(0, 0.5 / minimum distance between two points), dim: Q x D
    # the nyquist is half of maximum frequency. TODO
    nyquist = np.divide(0.5 ,min_dist)
    mixture_means = np.multiply(np.random.rand(num_mixtures,input_dim),\
                                                       np.expand_dims(nyquist,0))
    mixture_means[0,:] = 0

    # Mixture weights should be roughly the std  of the y values divided by
    # the number of mixtures
    # dim: 1 x Q
    mixture_weights= np.divide(np.std(train_y,axis=0),num_mixtures)*np.ones(num_mixtures)

    return mixture_weights, mixture_means, mixture_scales.T
```
[3] **Full stack of the error**:
```
Traceback (most recent call last):
  File "/l/gadichs1/conda_envs/deepgps_2_3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1323, in _do_call
    return fn(*args)
  File "/l/gadichs1/conda_envs/deepgps_2_3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1302, in _run_fn
    status, run_metadata)
  File "/l/gadichs1/conda_envs/deepgps_2_3/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Incompatible shapes: [100,4] vs. [10000,4]
	 [[Node: gradients/DGP-ca7720f0-47/add_grad/BroadcastGradientArgs = BroadcastGradientArgs[T=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"](gradients/DGP-ca7720f0-47/conditional/ExpandDims_7_grad/Shape, DGP-ca7720f0-47/conditional/Shape_5)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/l/gadichs1/gitrepos/aalto/Deep_Spectral_Kernels/demo/run_code.py", line 107, in <module>
    AdamOptimizer(0.01).minimize(m, maxiter=5000)
  File "/l/gadichs1/conda_envs/deepgps_2_3/lib/python3.5/site-packages/gpflow/training/tensorflow_optimizer.py", line 115, in minimize
    opt()
  File "/l/gadichs1/conda_envs/deepgps_2_3/lib/python3.5/site-packages/gpflow/actions.py", line 143, in __call__
    self.run(context)
  File "/l/gadichs1/conda_envs/deepgps_2_3/lib/python3.5/site-packages/gpflow/actions.py", line 365, in run
    context.session.run(self.optimizer_tensor, **self.run_kwargs)
  File "/l/gadichs1/conda_envs/deepgps_2_3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 889, in run
    run_metadata_ptr)
  File "/l/gadichs1/conda_envs/deepgps_2_3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1120, in _run
    feed_dict_tensor, options, run_metadata)
  File "/l/gadichs1/conda_envs/deepgps_2_3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1317, in _do_run
    options, run_metadata)
  File "/l/gadichs1/conda_envs/deepgps_2_3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1336, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Incompatible shapes: [100,4] vs. [10000,4]
	 [[Node: gradients/DGP-ca7720f0-47/add_grad/BroadcastGradientArgs = BroadcastGradientArgs[T=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"](gradients/DGP-ca7720f0-47/conditional/ExpandDims_7_grad/Shape, DGP-ca7720f0-47/conditional/Shape_5)]]

Caused by op 'gradients/DGP-ca7720f0-47/add_grad/BroadcastGradientArgs', defined at:
  File "/l/gadichs1/gitrepos/aalto/Deep_Spectral_Kernels/demo/run_code.py", line 107, in <module>
    AdamOptimizer(0.01).minimize(m, maxiter=5000)
  File "/l/gadichs1/conda_envs/deepgps_2_3/lib/python3.5/site-packages/gpflow/training/tensorflow_optimizer.py", line 107, in minimize
    feed_dict=feed_dict, **kwargs)
  File "/l/gadichs1/conda_envs/deepgps_2_3/lib/python3.5/site-packages/gpflow/training/tensorflow_optimizer.py", line 76, in make_optimize_action
    optimizer_tensor = self.make_optimize_tensor(model, session, var_list=var_list, **kwargs)
  File "/l/gadichs1/conda_envs/deepgps_2_3/lib/python3.5/site-packages/gpflow/training/tensorflow_optimizer.py", line 54, in make_optimize_tensor
    minimize = self.optimizer.minimize(objective, var_list=full_var_list, **kwargs)
  File "/l/gadichs1/conda_envs/deepgps_2_3/lib/python3.5/site-packages/tensorflow/python/training/optimizer.py", line 343, in minimize
    grad_loss=grad_loss)
  File "/l/gadichs1/conda_envs/deepgps_2_3/lib/python3.5/site-packages/tensorflow/python/training/optimizer.py", line 414, in compute_gradients
    colocate_gradients_with_ops=colocate_gradients_with_ops)
  File "/l/gadichs1/conda_envs/deepgps_2_3/lib/python3.5/site-packages/tensorflow/python/ops/gradients_impl.py", line 581, in gradients
    grad_scope, op, func_call, lambda: grad_fn(op, *out_grads))
  File "/l/gadichs1/conda_envs/deepgps_2_3/lib/python3.5/site-packages/tensorflow/python/ops/gradients_impl.py", line 353, in _MaybeCompile
    return grad_fn()  # Exit early
  File "/l/gadichs1/conda_envs/deepgps_2_3/lib/python3.5/site-packages/tensorflow/python/ops/gradients_impl.py", line 581, in <lambda>
    grad_scope, op, func_call, lambda: grad_fn(op, *out_grads))
  File "/l/gadichs1/conda_envs/deepgps_2_3/lib/python3.5/site-packages/tensorflow/python/ops/math_grad.py", line 714, in _AddGrad
    rx, ry = gen_array_ops._broadcast_gradient_args(sx, sy)
  File "/l/gadichs1/conda_envs/deepgps_2_3/lib/python3.5/site-packages/tensorflow/python/ops/gen_array_ops.py", line 532, in _broadcast_gradient_args
    "BroadcastGradientArgs", s0=s0, s1=s1, name=name)
  File "/l/gadichs1/conda_envs/deepgps_2_3/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/l/gadichs1/conda_envs/deepgps_2_3/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 2956, in create_op
    op_def=op_def)
  File "/l/gadichs1/conda_envs/deepgps_2_3/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1470, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

...which was originally created as op 'DGP-ca7720f0-47/add', defined at:
  File "/l/gadichs1/gitrepos/aalto/Deep_Spectral_Kernels/demo/run_code.py", line 100, in <module>
    m_dgp1 = make_dgp(X, Y, Z_100, 3, 3)
  File "/l/gadichs1/gitrepos/aalto/Deep_Spectral_Kernels/demo/run_code.py", line 57, in make_dgp
    minibatch_size=mb)
  File "/l/gadichs1/conda_envs/deepgps_2_3/lib/python3.5/site-packages/gpflow/core/compilable.py", line 90, in __init__
    self.build()
  File "/l/gadichs1/conda_envs/deepgps_2_3/lib/python3.5/site-packages/gpflow/core/node.py", line 156, in build
    self._build()
  File "/l/gadichs1/conda_envs/deepgps_2_3/lib/python3.5/site-packages/gpflow/models/model.py", line 81, in _build
    likelihood = self._build_likelihood()
  File "/l/gadichs1/conda_envs/deepgps_2_3/lib/python3.5/site-packages/gpflow/decors.py", line 67, in tensor_mode_wrapper
    result = method(obj, *args, **kwargs)
  File "/l/gadichs1/gitrepos/aalto/Deep_Spectral_Kernels/deep_spectral_kernel/dgp.py", line 88, in _build_likelihood
    L = tf.reduce_sum(self.E_log_p_Y(self.X, self.Y))
  File "/l/gadichs1/gitrepos/aalto/Deep_Spectral_Kernels/deep_spectral_kernel/dgp.py", line 82, in E_log_p_Y
    Fmean, Fvar = self._build_predict(X, full_cov=False, S=self.num_samples)
  File "/l/gadichs1/conda_envs/deepgps_2_3/lib/python3.5/site-packages/gpflow/decors.py", line 67, in tensor_mode_wrapper
    result = method(obj, *args, **kwargs)
  File "/l/gadichs1/gitrepos/aalto/Deep_Spectral_Kernels/deep_spectral_kernel/dgp.py", line 74, in _build_predict
    Fs, Fmeans, Fvars = self.propagate(X, full_cov=full_cov, S=S)
  File "/l/gadichs1/conda_envs/deepgps_2_3/lib/python3.5/site-packages/gpflow/decors.py", line 67, in tensor_mode_wrapper
    result = method(obj, *args, **kwargs)
  File "/l/gadichs1/gitrepos/aalto/Deep_Spectral_Kernels/deep_spectral_kernel/dgp.py", line 64, in propagate
    F, Fmean, Fvar = layer.sample_from_conditional(F, z=z, full_cov=full_cov)
  File "/l/gadichs1/gitrepos/aalto/Deep_Spectral_Kernels/deep_spectral_kernel/layers.py", line 106, in sample_from_conditional
    mean, var = self.conditional(X, full_cov=full_cov)
  File "/l/gadichs1/gitrepos/aalto/Deep_Spectral_Kernels/deep_spectral_kernel/layers.py", line 91, in conditional
    mean, var = single_sample_conditional(X_flat)

InvalidArgumentError (see above for traceback): Incompatible shapes: [100,4] vs. [10000,4]
	 [[Node: gradients/DGP-ca7720f0-47/add_grad/BroadcastGradientArgs = BroadcastGradientArgs[T=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"](gradients/DGP-ca7720f0-47/conditional/ExpandDims_7_grad/Shape, DGP-ca7720f0-47/conditional/Shape_5)]]
```

**Comment by hughsalimbeni** [comment]
Can you include the code where you build the model? If you're using the MultiClass kernel you need to pass `num_outputs` or things won't work properly

**Comment by imsrgadich** [comment]
here it is, i'm not using a `Multiclass` kernel. 

```
def make_dgp(X, Y, Z, L, Q):
    """
    X - input data locations
    Y - target data
    Z - inducing points
    L - Number of layers
    Q - Number of Spectral components
    """
    D = X.shape[1]

    # the layer shapes are defined by the kernel dims, so here all
    # hidden layers are D dimensional
    kernels = []
    for l in range(L):
        weights, means, scales = sm_init(train_x=X, train_y=Y, num_mixtures=Q)

        kern = SpectralMixture(num_mixtures=Q, mixture_weights=weights,
                               mixture_scales=scales, mixture_means=means,
                               input_dim=D)
        kernels.append(kern)

    # between layer noise (doesn't actually make much difference
    # but we include it anyway)
    for kernel in kernels[:-1]:
        kernel += White(D, variance=1e-5)

    mb = 1000 if X.shape[0] > 1000 else None
    model = DGP(X, Y, Z, kernels, Gaussian(), num_samples=10, \
                minibatch_size=mb)

    # start the inner layers almost deterministically
    for layer in model.layers[:-1]:
        layer.q_sqrt = layer.q_sqrt.value * 1e-5

    return model
```

**Comment by hughsalimbeni** [comment]
I haven't investigated the kernel code above, but the below fails for me:

```python
N, Ns, D, Q = 5, 4, 3, 2

X = np.random.randn(N, D)
Y = np.random.randn(N, 1)
Xs = np.random.randn(Ns, D)

weights, means, scales = sm_init(train_x=X, train_y=Y, num_mixtures=Q)

kern = SpectralMixture(num_mixtures=Q, 
                       mixture_weights=weights, 
                       mixture_means=means, 
                       mixture_scales=scales,
                       input_dim=D)

print(kern.compute_K(X, Xs))  # should be shape (N, Ns)
```

This is causing the error when I try using it in the DGP

**Comment by imsrgadich** [comment]
yeah that was the error. thanks!
